language: python

install:
  pip install -r requirements.txt

jobs:
    include:
      - stage: test
        script:
        - pytest 
      - stage: pages
        script:
        - cd docs && make html
        - mv build/html ../public

notifications:
  email:
    recipients:
      - leia@ssi.gouv.fr
    on_success: never
    on_failure: always
    on_pull_requests: always

