language: python
python:
  - "3.7"

install:
  pip install -r requirements.txt

jobs:
    include:
      - stage: test
        script:
        # Test the package compilation and installation
        - pytest 
        - python3 -m pip install smartleia
        # Now test the documentation compilation
        - pip install poetry
        - cd docs && make html

notifications:
  email:
    recipients:
      - leia@ssi.gouv.fr
    on_success: never
    on_failure: always
    on_pull_requests: always

