language: python
python:
  - "3.7"

install:
  pip install -r requirements.txt

jobs:
    include:
      - stage: test
        script:
        # Test the package compilation and installation
        - pytest
        - pip install --upgrade setuptools
        - pip install smartleia

notifications:
  email:
    recipients:
      - leia@ssi.gouv.fr
    on_success: never
    on_failure: always
    on_pull_requests: always

